-- RegisterServerEvent("Fleeca:success:lockpick")
-- AddEventHandler("Fleeca:success:lockpick", function()
--         local pSrc = source
--         TriggerClientEvent('player:receiveItem', pSrc, 'cashstack', math.random(1,10))
--     else
--         TriggerClientEvent('player:receiveItem', pSrc, 'goldbar', math.random(1,5))
-- end)