-- ## TABLES ## --
WsT = {}

WsT.AllowedCountrys = {"GB","US","BE","FR","DE"} -- https://www.iban.com/country-codes - Use ALPHA-2 codes

WsT.BlacklistedNames = {"[A]", "[F]","[M]","[H]", "[S]", "admin", "moderator","owner", "founder", ".com", ".gg", "nigga", "youtube", ".be", "anticheat"} -- IF PLAYER NAME CONTAINS ONE OF THESE WORDS HE IS KICKED
WsT.BlacklistedCommands = { 'pk', 'haha', 'lol', 'xddd', 'chocolate', 'panickey', 'jolmany', 'killmenu' }

WsT.BlacklistedWords = {'Desudo', 'Brutan', 'EulenCheats', "discord.gg/", "lynxmenu", "HamHaxia", "Ham Mafia", "www.renalua.com", "Fallen#0811", "Rena 8", "HamHaxia",
"Ham Mafia", "Xanax#0134", ">:D Player Crash", "discord.gg", "34ByTe Community", "lynxmenu.com", "Anti-LRAC", "Baran#8992", "iLostName#7138", "85.190.90.118", "Melon#1379",
"hammafia.com", "AlphaV ~ 5391", "vjuton.pl", "Soviet Bear", "XARIES", "xaries", "dc.xaries.pl", "aries", "aries.pl", "youtube.com/c/Aries98/", "Aries98", "yo many", "dezet",
"333", "333GANG" }

WsT.BlacklistedExplosions = { -- DETECT IF A PLAYER SPAWN THESE EXPLOSIONS TYPES
	[0] = { name = "Grenade", detect = true, ban = true},
    [1] = { name = "GrenadeLauncher", detect = true, ban = true},
    [3] = { name = "Molotov", detect = true, ban = true},
    [4] = { name = "Rocket", detect = true, ban = true},
    [5] = { name = "TankShell", detect = true, ban = true},
    [6] = { name = "Hi_Octane", detect = true, ban = true},
    [7] = { name = "Car", detect = true, ban = true},
    [8] = { name = "Plance", detect = true, ban = true},
    [9] = { name = "PetrolPump", detect = true, ban = true},
    [10] = { name = "Bike", detect = true, ban = true},
    [11] = { name = "Dir_Steam", detect = true, ban = true},
    [12] = { name = "Dir_Flame", detect = true, ban = true},
    [13] = { name = "Dir_Water_Hydrant", detect = true, ban = true},
    [14] = { name = "Dir_Gas_Canister", detect = true, ban = true},
    [15] = { name = "Boat", detect = true, ban = true},
    [16] = { name = "Ship_Destroy", detect = true, ban = true},
    [17] = { name = "Truck", detect = true, ban = true},
    [18] = { name = "Bullet", detect = true, ban = true},
    [19] = { name = "SmokeGrenadeLauncher", detect = true, ban = true},
    [20] = { name = "SmokeGrenade", detect = true, ban = true},
    [21] = { name = "BZGAS", detect = true, ban = true},
    [22] = { name = "Flare", detect = true, ban = true},
    [23] = { name = "Gas_Canister", detect = true, ban = true},
    [24] = { name = "Extinguisher", detect = true, ban = true},
    [25] = { name = "Programmablear",detect = true, ban = true},
    [26] = { name = "Train", detect = true, ban = true},
    [27] = { name = "Barrel", detect = true, ban = true},
    [28] = { name = "PROPANE", detect = true, ban = true},
    [29] = { name = "Blimp", detect = true, ban = true},
    [30] = { name = "Dir_Flame_Explode", detect = true, ban = true},
    [31] = { name = "Tanker", detect = true, ban = true},
    [32] = { name = "PlaneRocket", detect = true, ban = true},
    [33] = { name = "VehicleBullet", detect = true, ban = true},
    [34] = { name = "Gas_Tank", detect = true, ban = true},
    [35] = { name = "FireWork", detect = true, ban = true},
    [36] = { name = "SnowBall", detect = true, ban = true},
    [37] = { name = "ProxMine", detect = true, ban = true},
    [38] = { name = "Valkyrie_Cannon", detect = true, ban = true},
}

WsT.BlacklistedWeapons = { -- Blacklisted weapons
    'WEAPON_GRENADELAUNCHER',
	'WEAPON_RPG',
	'WEAPON_STINGER',
	'WEAPON_MINIGUN',
	'WEAPON_GRENADE',
	'WEAPON_STICKYBOMB',
	'WEAPON_RAILGUN',
	'WEAPON_COMPACTLAUNCHER',
	'WEAPON_PIPEBOMB',
	'WEAPON_PROXMINE',
	'WEAPON_GRENADELAUNCHER_SMOKE',
	'WEAPON_FIREWORK',
	'WEAPON_HOMINGLAUNCHER',
	'WEAPON_RAYPISTOL',
	'WEAPON_RAYCARBINE',
	'WEAPON_RAYMINIGUN',
	'WEAPON_DIGISCANNER',
}

WsT.BlacklistedPickups = { -- DONT MODIFY ` to " or ' !!! ALL IS ALREADY BLACKLIST :)
	`PICKUP_WEAPON_STONE_HATCHET`,
	`PICKUP_WEAPON_DOUBLEACTION`,
	`PICKUP_WEAPON_ASSAULTRIFLE_MK2`,
	`PICKUP_WEAPON_BULLPUPRIFLE_MK2`,
	`PICKUP_WEAPON_CARBINERIFLE_MK2`,
	`PICKUP_WEAPON_COMBATMG_MK2`,
	`PICKUP_WEAPON_HEAVYSNIPER_MK2`,
	`PICKUP_WEAPON_MARKSMANRIFLE_MK2`,
	`PICKUP_WEAPON_PISTOL_MK2`,
	`PICKUP_WEAPON_PUMPSHOTGUN_MK2`,
	`PICKUP_WEAPON_REVOLVER_MK2`,
	`PICKUP_WEAPON_SMG_MK2`,
	`PICKUP_WEAPON_SNSPISTOL_MK2`,
	`PICKUP_WEAPON_SPECIALCARBINE_MK2`,
	`PICKUP_AMMO_BULLET_MP`,
    `PICKUP_AMMO_FIREWORK`,
    `PICKUP_AMMO_FLAREGUN`,
    `PICKUP_AMMO_GRENADELAUNCHER`,
    `PICKUP_AMMO_GRENADELAUNCHER_MP`,
    `PICKUP_AMMO_HOMINGLAUNCHER`,
    `PICKUP_AMMO_MG`,
    `PICKUP_AMMO_MINIGUN`,
    `PICKUP_AMMO_MISSILE_MP`,
    `PICKUP_AMMO_PISTOL`,
    `PICKUP_AMMO_RIFLE`,
    `PICKUP_AMMO_RPG`,
    `PICKUP_AMMO_SHOTGUN`,
    `PICKUP_AMMO_SMG`,
    `PICKUP_AMMO_SNIPER`,
    `PICKUP_ARMOUR_STANDARD`,
    `PICKUP_CAMERA`,
    `PICKUP_CUSTOM_SCRIPT`,
    `PICKUP_GANG_ATTACK_MONEY`,
    `PICKUP_HEALTH_SNACK`,
    `PICKUP_HEALTH_STANDARD`,
    `PICKUP_MONEY_CASE`,
    `PICKUP_MONEY_DEP_BAG`,
    `PICKUP_MONEY_MED_BAG`,
    `PICKUP_MONEY_PAPER_BAG`,
    `PICKUP_MONEY_PURSE`,
    `PICKUP_MONEY_SECURITY_CASE`,
    `PICKUP_MONEY_VARIABLE`,
    `PICKUP_MONEY_WALLET`,
    `PICKUP_PARACHUTE`,
    `PICKUP_PORTABLE_CRATE_FIXED_INCAR`,
    `PICKUP_PORTABLE_CRATE_UNFIXED`,
    `PICKUP_PORTABLE_CRATE_UNFIXED_INCAR`,
    `PICKUP_PORTABLE_CRATE_UNFIXED_INCAR_SMALL`,
    `PICKUP_PORTABLE_CRATE_UNFIXED_LOW_GLOW`,
    `PICKUP_PORTABLE_DLC_VEHICLE_PACKAGE`,
    `PICKUP_PORTABLE_PACKAGE`,
    `PICKUP_SUBMARINE`,
    `PICKUP_VEHICLE_ARMOUR_STANDARD`,
    `PICKUP_VEHICLE_CUSTOM_SCRIPT`,
    `PICKUP_VEHICLE_CUSTOM_SCRIPT_LOW_GLOW`,
    `PICKUP_VEHICLE_HEALTH_STANDARD`,
    `PICKUP_VEHICLE_HEALTH_STANDARD_LOW_GLOW`,
    `PICKUP_VEHICLE_MONEY_VARIABLE`,
    `PICKUP_VEHICLE_WEAPON_APPISTOL`,
    `PICKUP_VEHICLE_WEAPON_ASSAULTSMG`,
    `PICKUP_VEHICLE_WEAPON_COMBATPISTOL`,
    `PICKUP_VEHICLE_WEAPON_GRENADE`,
    `PICKUP_VEHICLE_WEAPON_MICROSMG`,
    `PICKUP_VEHICLE_WEAPON_MOLOTOV`,
    `PICKUP_VEHICLE_WEAPON_PISTOL`,
    `PICKUP_VEHICLE_WEAPON_PISTOL50`,
    `PICKUP_VEHICLE_WEAPON_SAWNOFF`,
    `PICKUP_VEHICLE_WEAPON_SMG`,
    `PICKUP_VEHICLE_WEAPON_SMOKEGRENADE`,
    `PICKUP_VEHICLE_WEAPON_STICKYBOMB`,
    `PICKUP_WEAPON_ADVANCEDRIFLE`,
    `PICKUP_WEAPON_APPISTOL`,
    `PICKUP_WEAPON_ASSAULTRIFLE`,
    `PICKUP_WEAPON_ASSAULTSHOTGUN`,
    `PICKUP_WEAPON_ASSAULTSMG`,
    `PICKUP_WEAPON_AUTOSHOTGUN`,
    `PICKUP_WEAPON_BAT`,
    `PICKUP_WEAPON_BATTLEAXE`,
    `PICKUP_WEAPON_BOTTLE`,
    `PICKUP_WEAPON_BULLPUPRIFLE`,
    `PICKUP_WEAPON_BULLPUPSHOTGUN`,
    `PICKUP_WEAPON_CARBINERIFLE`,
    `PICKUP_WEAPON_COMBATMG`,
    `PICKUP_WEAPON_COMBATPDW`,
    `PICKUP_WEAPON_COMBATPISTOL`,
    `PICKUP_WEAPON_COMPACTLAUNCHER`,
    `PICKUP_WEAPON_COMPACTRIFLE`,
    `PICKUP_WEAPON_CROWBAR`,
    `PICKUP_WEAPON_DAGGER`,
    `PICKUP_WEAPON_DBSHOTGUN`,
    `PICKUP_WEAPON_FIREWORK`,
    `PICKUP_WEAPON_FLAREGUN`,
    `PICKUP_WEAPON_FLASHLIGHT`,
    `PICKUP_WEAPON_GRENADE`,
    `PICKUP_WEAPON_GRENADELAUNCHER`,
    `PICKUP_WEAPON_GUSENBERG`,
    `PICKUP_WEAPON_GOLFCLUB`,
    `PICKUP_WEAPON_HAMMER`,
    `PICKUP_WEAPON_HATCHET`,
    `PICKUP_WEAPON_HEAVYPISTOL`,
    `PICKUP_WEAPON_HEAVYSHOTGUN`,
    `PICKUP_WEAPON_HEAVYSNIPER`,
    `PICKUP_WEAPON_HOMINGLAUNCHER`,
    `PICKUP_WEAPON_KNIFE`,
    `PICKUP_WEAPON_KNUCKLE`,
    `PICKUP_WEAPON_MACHETE`,
    `PICKUP_WEAPON_MACHINEPISTOL`,
    `PICKUP_WEAPON_MARKSMANPISTOL`,
    `PICKUP_WEAPON_MARKSMANRIFLE`,
    `PICKUP_WEAPON_MG`,
    `PICKUP_WEAPON_MICROSMG`,
    `PICKUP_WEAPON_MINIGUN`,
    `PICKUP_WEAPON_MINISMG`,
    `PICKUP_WEAPON_MOLOTOV`,
    `PICKUP_WEAPON_MUSKET`,
    `PICKUP_WEAPON_NIGHTSTICK`,
    `PICKUP_WEAPON_PETROLCAN`,
    `PICKUP_WEAPON_PIPEBOMB`,
    `PICKUP_WEAPON_PISTOL`,
    `PICKUP_WEAPON_PISTOL50`,
    `PICKUP_WEAPON_POOLCUE`,
    `PICKUP_WEAPON_PROXMINE`,
    `PICKUP_WEAPON_PUMPSHOTGUN`,
    `PICKUP_WEAPON_RAILGUN`,
    `PICKUP_WEAPON_REVOLVER`,
    `PICKUP_WEAPON_RPG`,
    `PICKUP_WEAPON_SAWNOFFSHOTGUN`,
    `PICKUP_WEAPON_SMG`,
    `PICKUP_WEAPON_SMOKEGRENADE`,
    `PICKUP_WEAPON_SNIPERRIFLE`,
    `PICKUP_WEAPON_SNSPISTOL`,
    `PICKUP_WEAPON_SPECIALCARBINE`,
    `PICKUP_WEAPON_STICKYBOMB`,
    `PICKUP_WEAPON_STUNGUN`,
    `PICKUP_WEAPON_SWITCHBLADE`,
    `PICKUP_WEAPON_VINTAGEPISTOL`,
    `PICKUP_WEAPON_WRENCH`,
    `PICKUP_WEAPON_RAYCARBINE`
}

WsT.WhitelistedProps = { -- WHITELISTED PROPS ( AUTHORIZED TO SPAWN ) ! ( MODEL HASH OR MODEL NAME )
	"prop_ballistic_shield",
	260873931,
}

WsT.WhitelistedParticles = { -- WHITELISTED PARTICLES ( AUTHORIZED TO SPAWN ) ! ( MODEL HASH OR MODEL NAME )
	"veh_backfire"
}

WsT.BlacklistedModels = { -- Blacklisted models ( PEDS / VEHICLES ) ( MODEL HASH OR MODEL NAME )
	"skylift",
	"valkyrie2",
	"airbus",
	"hunter",
	"bus",
	"armytanker",
	"armytrailer",
	"armytrailer2",
	"baletrailer",
	"boattrailer",
	"cablecar",
	"docktrailer",
	"freighttrailer",
	"graintrailer",
	"proptrailer",
	"raketrailer",
	"tr2",
	"tug",
	"tr3",
	"tr4",
	"trflat",
	"tvtrailer",
	"tanker",
	"tanker2",
	"trailerlarge",
	"trailerlogs",
	"trailersmall",
	"trailers",
	"trailers2",
	"trailers3",
	"trailers4",
	'RHINO',
	'AKULA',
	'SAVAGE',
	'HUNTER',
	'BUZZARD',
	'BUZZARD2',
	'ANNIHILATOR',
	'VALKYRIE',
	'HYDRA',
	'APC',
	'Trailersmall2',
	'Lazer',
	'oppressor',
	'mogul',
	'barrage',
	'Khanjali',
	'volatol',
	'chernobog',
	'avenger',
	'stromberg',
	'nightshark',
	'besra',
	'babushka ',
	'starling',
	'insurgent',
	'cargobob',
	'cargobob2',
	'cargobob3',
	'cargobob4',
	'caracara',
	'deluxo',
	'menacer',
    'scramjet',
    'oppressor2',
    'revolter',
    'viseris',
    'savestra',
    'thruster',
    'ardent',
    'dune3',
    'tampa3',
    'halftrack',
    'nokota',
    'strikeforce',
    'bombushka',
    'molotok',
    'pyro',
    'ruiner2',
    'limo2',
    'technical',
    'technical2',
    'technical3',
    'jb700w',
    'blazer5',
    'insurgent3',
	'boxville5',
	'bruiser',
    'bruiser2',
    'bruiser3',
    'brutus',
    'brutus2',
    'brutus3',
    'cerberus',
    'cerberus2',
    'cerberus3',
    'dominator4',
    'dominator5',
    'dominator6',
    'impaler2',
    'impaler3',
    'impaler4',
    'imperator',
    'imperator2',
    'imperator3',
    'issi4',
    'issi5',
    'issi6',
    'monster3',
    'monster4',
    'monster5',
    'scarab',
    'scarab2',
    'scarab3',
    'slamvan4',
    'slamvan5',
    'slamvan6',
    'zr380',
    'zr3802',
    'zr3803',
	'alphaz1',
	'avenger2',
	'blimp',
	'blimp2',
	'blimp3',
	'cargoplane',
	'cuban800',
	'dodo',
	'duster',
	'howard',
	'jet',
	'luxor',
	'luxor2',
	'mammatus',
	'microlight',
	'miljet',
	'nimbus',
	'rogue',
	'seabreeze',
	'shamal',
	'stunt',
	'titan',
	'tula',
	'velum',
	'velum2',
	'vestra',

	"s_m_y_swat_01",
	"a_m_o_acult_01",
	"ig_wade",
	"s_m_y_hwaycop_01",
	"A_M_Y_ACult_01",
	's_m_m_movalien_01',
	's_m_m_movallien_01',
	'u_m_y_babyd',
	'CS_Orleans',
	'A_M_Y_ACult_01',
	'S_M_M_MovSpace_01',
	'U_M_Y_Zombie_01',
	's_m_y_blackops_01',
	'a_f_y_topless_01',
	'a_c_boar',
	'a_c_cat_01',
	'a_c_chickenhawk',
	'a_c_chimp',
	's_f_y_hooker_03',
	'a_c_chop',
	'a_c_cormorant',
	'a_c_cow',
	'a_c_coyote',
	'a_c_crow',
	'a_c_dolphin',
	'a_c_fish',
	's_f_y_hooker_01',
	'a_c_hen',
	'a_c_humpback',
	'a_c_husky',
	'a_c_killerwhale',
	'a_c_mtlion',
	'a_c_pigeon',
	'a_c_poodle',
	'a_c_pug',
	'a_c_rabbit_01',
	'a_c_rat',
	'a_c_retriever',
	'a_c_rhesus',
	'a_c_rottweiler',
	'a_c_sharkhammer',
	'a_c_sharktiger',
	'a_c_shepherd',
	'a_c_stingray',
	'a_c_westy',
	'CS_Orleans',
}

WsT.ProtectedEvents = { --secure here all triggers you entered
	"my_event_name",
}

WsT.BlacklistedEvents = { -- Blacklisted triggers / events
	"gcPhone:_internalAddMessage",
	"gcPhone:tchat_channel",
	"esx_vehicleshop:setVehicleOwned",
	"esx_mafiajob:confiscatePlayerItem",
	"lscustoms:payGarage",
	"vrp_slotmachine:server:2",
	"Banca:deposit",
	"bank:deposit",
	"esx_jobs:caution",
	"give_back",
	"esx_fueldelivery:pay",
	"esx_carthief:pay",
	"esx_godirtyjob:pay",
	"esx_pizza:pay",
	"esx_ranger:pay",
	"esx_garbagejob:pay",
	"esx_truckerjob:pay",
	"redst0nia:checking",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"esx_gopostaljob:pay",
	"esx_banksecurity:pay",
	"esx_slotmachine:sv:2",
	"esx:giveInventoryItem",
	"NB:recruterplayer",
	"esx_billing:sendBill",
	"esx_jailer:sendToJail",
	"esx_jail:sendToJail",
	"js:jailuser",
	"esx-qalle-jail:jailPlayer",
	"esx_dmvschool:pay", 
	"LegacyFuel:PayFuel",
	"OG_cuffs:cuffCheckNearest",
	"CheckHandcuff",
	"cuffServer",
	"cuffGranted",
	"police:cuffGranted",
	"esx_handcuffs:cuffing",
	"esx_policejob:handcuff",
	"bank:withdraw",
	"dmv:success",
	"esx_skin:responseSaveSkin",
	"esx_dmvschool:addLicense",
	"esx_mechanicjob:startCraft",
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startSellWeed",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startSellCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startSellMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startSellOpium",
	"esx_drugs:startTransformOpium",
	"esx_blanchisseur:startWhitening",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopTransformWeed",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:stopSellOpium",
	"esx_society:openBossMenu",
	"esx_jobs:caution",
	"esx_tankerjob:pay",
	"esx_vehicletrunk:giveDirty",
	"gambling:spend",
	"AdminMenu:giveDirtyMoney",
	"esx_moneywash:deposit",
	"esx_moneywash:withdraw",
	"mission:completed",
	"truckerJob:success",
	"99kr-burglary:addMoney",
	"esx_jailer:unjailTime",
	"esx_ambulancejob:revive",
	"DiscordBot:playerDied",
	"hentailover:xdlol",
	"antilynx8:anticheat",
	"antilynxr6:detection",
	"esx:getSharedObject",
	"esx_society:getOnlinePlayers",
	"_chat:messageEntered",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"js:jailuser", 
	"ynx8:anticheat",
	"lynx8:anticheat",
	"adminmenu:allowall",
	"h:xd",
	"ljail:jailplayer",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"bank:transfer",
	"paycheck:bonus",
	"paycheck:salary",
	"HCheat:TempDisableDetection",
	"esx_drugs:pickedUpCannabis",
	"esx_drugs:processCannabis",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_mecanojob:onNPCJobCompleted",
	"BsCuff:Cuff696999",
	"veh_SR:CheckMoneyForVeh",
	"esx_carthief:alertcops",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"esx_society:putVehicleInGarage",
}

WsT.WeaponDamageList = { -- DO NOT TOUCH
	[453432689] = 26.0, -- WEAPON_PISTOL
	[1593441988] = 27.0, -- WEAPON_COMBATPISTOL
	[584646201] = 25.0, -- WEAPON_APPISTOL
	[-1716589765] = 51.0, -- WEAPON_PISTOL50
	[324215364] = 21.0, -- WEAPON_MICROSMG
	[736523883] = 22.0, -- WEAPON_SMG
	[-270015777] = 23.0, -- WEAPON_ASSAULTSMG
	[-1074790547] = 30.0, -- WEAPON_ASSAULTRIFLE
	[-2084633992] = 32.0, -- WEAPON_CARBINERIFLE
	[-1357824103] = 34.0, -- WEAPON_ADVANCEDRIFLE
	[-1660422300] = 40.0, -- WEAPON_MG
	[2144741730] = 45.0, -- WEAPON_COMBATMG
	[487013001] = 29.0, -- WEAPON_PUMPSHOTGUN
	[2017895192] = 40.0, -- WEAPON_SAWNOFFSHOTGUN
	[-494615257] = 32.0, -- WEAPON_ASSAULTSHOTGUN
	[-1654528753] = 14.0, -- WEAPON_BULLPUPSHOTGUN
	[100416529] = 101.0, -- WEAPON_SNIPERRIFLE
	[205991906] = 216.0, -- WEAPON_HEAVYSNIPER
	[1119849093] = 30.0, -- WEAPON_MINIGUN
	[-1076751822] = 28.0, -- WEAPON_SNSPISTOL
	[1627465347] = 34.0, -- WEAPON_GUSENBERG
	[-1063057011] = 32.0, -- WEAPON_SPECIALCARBINE
	[-771403250] = 40.0, -- WEAPON_HEAVYPISTOL
	[2132975508] = 32.0, -- WEAPON_BULLPUPRIFLE
	[137902532] = 34.0, -- WEAPON_VINTAGEPISTOL
	[-1466123874] = 165.0, -- WEAPON_MUSKET
	[984333226] = 117.0, -- WEAPON_HEAVYSHOTGUN
	[-952879014] = 65.0, -- WEAPON_MARKSMANRIFLE
	[1198879012] = 10.0, -- WEAPON_FLAREGUN
	[171789620] = 28.0, -- WEAPON_COMBATPDW
	[-598887786] = 220.0, -- WEAPON_MARKSMANPISTOL
	[-619010992] = 27.0, -- WEAPON_MACHINEPISTOL
	[-275439685] = 30.0, -- WEAPON_DBSHOTGUN
	[1649403952] = 34.0, -- WEAPON_COMPACTRIFLE
	[317205821] = 27.0, -- WEAPON_AUTOSHOTGUN
	[-1121678507] = 22.0, -- WEAPON_MINISMG
	[-2009644972] = 30.0, -- WEAPON_SNSPISTOL_MK2
	[-1768145561] = 32.5, -- WEAPON_SPECIALCARBINE_MK2
	[-2066285827] = 33.0, -- WEAPON_BULLPUPRIFLE_MK2
	[1432025498] = 32.0, -- WEAPON_PUMPSHOTGUN_MK2
	[1785463520] = 75.0, -- WEAPON_MARKSMANRIFLE_MK2
	[961495388] = 40.0, -- WEAPON_ASSAULTRIFLE_MK2
	[-86904375] = 33.0, -- WEAPON_CARBINERIFLE_MK2
	[-608341376] = 47.0, -- WEAPON_COMBATMG_MK2
	[177293209] = 230.0, -- WEAPON_HEAVYSNIPER_MK2
	[-1075685676] = 32.0, -- WEAPON_PISTOL_MK2
	[2024373456] = 25.0 -- WEAPON_SMG_MK2
}